# Generated by Django 4.1.3 on 2022-11-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_dislike', models.CharField(max_length=32)),
                ('description_dislike', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, upload_to='photoUser')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LikeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_like', models.CharField(max_length=32)),
                ('description_like', models.CharField(max_length=200)),
                ('for_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.grademodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('amount_likes', models.IntegerField(default=6)),
                ('amount_dislikes', models.IntegerField(default=2)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='liketable',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.usertelegram'),
        ),
        migrations.AddField(
            model_name='disliketable',
            name='for_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.grademodel'),
        ),
        migrations.AddField(
            model_name='disliketable',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.usertelegram'),
        ),
    ]
