# Generated by Django 4.1.3 on 2022-11-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0003_usertelegram_id_tg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disliketable',
            old_name='description_dislike',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='disliketable',
            old_name='reason_dislike',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='liketable',
            old_name='description_like',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='liketable',
            old_name='reason_like',
            new_name='reason',
        ),
    ]
