# Generated by Django 4.1.3 on 2022-11-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0004_rename_description_dislike_disliketable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademodel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='liketable',
            name='for_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.grademodel', to_field='name'),
        ),
        migrations.AlterField(
            model_name='liketable',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.usertelegram', to_field='userName'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='userName',
            field=models.TextField(unique=True),
        ),
    ]
