# Generated by Django 4.1.3 on 2022-11-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0005_alter_grademodel_name_alter_liketable_for_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disliketable',
            name='for_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.grademodel', to_field='name'),
        ),
        migrations.AlterField(
            model_name='disliketable',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indexApp.usertelegram', to_field='userName'),
        ),
    ]
