# Generated by Django 4.1.3 on 2022-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0006_alter_disliketable_for_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grademodel',
            name='general',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
