# Generated by Django 4.1.3 on 2022-11-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0007_grademodel_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademodel',
            name='general',
            field=models.IntegerField(default=0),
        ),
    ]
